name: Deploy to GitHub Releases

on:
  push:
    branches:
      - master

jobs:
  deploy-to-github-releases:
    permissions: write-all
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish Application
      run: dotnet publish WeMeetRecorder/WeMeetRecorder.csproj -c Release -o publish -r win-x64 --self-contained false
    - name: Create Velopack Release
      env:
        BUILD_NUMBER: ${{github.run_number}}
      shell: pwsh
      run: |
        $Version = Get-Date -Format "yyyy.M.$env:BUILD_NUMBER"
        dotnet tool install -g vpk
        vpk download github --repoUrl https://github.com/ModerRAS/WeMeetRecorder
        vpk pack -u WeMeetRecorder -v $Version -p publish
        vpk upload github --repoUrl https://github.com/ModerRAS/WeMeetRecorder --publish --releaseName "WeMeetRecorder $Version" --tag latest --token ${{ secrets.GITHUB_TOKEN }}